### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/telegram_ros#15]
Put `telegram_ros` in rosdistro or switch to our own CI.

**Comment by Timple** [comment]
It's a fairly standalone package not related directly to our bots. So I think the industrial-ci is actualy nice

**Comment by LoyVanBeek** [comment]
It's in rosdistro, but not as a binary release: https://github.com/ros/rosdistro/blob/d31dc18ea27680d370e759d509cf81fca6e1a23f/kinetic/distribution.yaml#L14532

**Comment by Timple** [comment]
Oehhh, wil this be the first binary release? :D

**Comment by MatthijsBurgh** [comment]
Ok, I don't know why the CI failed before. But problem solved.

**Comment by LoyVanBeek** [comment]
> Oehhh, wil this be the first binary release? :D 

I spent a bit of time on this, but it's a long process to go though.
Any help towards that is welcome :-)
